@echo off
echo Starting AI Desktop Pet Final Demo...
set DESKTOP_PET_USER_STATE_ENABLED=false
set DESKTOP_PET_GESTURE_ENABLED=false
set DESKTOP_PET_MOCK_USER_STATE=false
set DESKTOP_PET_CAMERA_WIDTH=320
set DESKTOP_PET_CAMERA_HEIGHT=240
set DESKTOP_PET_CAMERA_READ_INTERVAL=0.07
set DESKTOP_PET_USER_DETECT_INTERVAL=1.0
set DESKTOP_PET_GESTURE_DETECT_INTERVAL=0.25
set DESKTOP_PET_GESTURE_POLL_MS=200
set DESKTOP_PET_VISION_DEBUG_REFRESH_MS=300
set DESKTOP_PET_QWEN_VL_ENABLED=false
set DESKTOP_PET_DEEPFACE_ENABLED=false
set DESKTOP_PET_FACE_MIMIC_ENABLED=false
python -m app.main
pause
